"use client";
import { ArrowRight, Mic, Fingerprint, Compass, ShieldCheck, Sprout, MapPin, HeartHandshake, BriefcaseBusiness, Check, Route, Users } from "lucide-react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { type Locale, t } from "@/lib/i18n";
import { LeapMark } from "./logo";
import { words as w } from "./primitives";

export function LandingPage({locale,startHref}:{locale:Locale;startHref:string}) {
 const router=useRouter();
 const factors=[
 [Fingerprint,w(locale,"Skills & experience","திறன்கள் மற்றும் அனுபவம்","कौशल और अनुभव"),w(locale,"The work you already know, with or without a certificate.","சான்றிதழ் இருந்தாலும் இல்லாவிட்டாலும் உங்களுக்குத் தெரிந்த வேலை.","प्रमाणपत्र हो या न हो, वह काम जो आप जानते हैं।")],
 [Compass,w(locale,"Your aspirations","உங்கள் விருப்பங்கள்","आपकी आकांक्षाएँ"),w(locale,"What you want to do next matters as much as your past.","கடந்த அனுபவத்தைப் போலவே உங்கள் எதிர்கால விருப்பமும் முக்கியம்.","आप आगे क्या करना चाहते हैं, यह भी उतना ही जरूरी है।")],
 [MapPin,w(locale,"Where life takes you","உங்கள் பயண வரம்பு","यात्रा की सुविधा"),w(locale,"Travel distance and local access shape what is practical.","பயண தூரமும் உள்ளூர் வாய்ப்புகளும் கருத்தில் கொள்ளப்படுகின்றன.","यात्रा की दूरी और स्थानीय सुविधा को ध्यान में रखा जाता है।")],
 [HeartHandshake,w(locale,"Your responsibilities","உங்கள் பொறுப்புகள்","आपकी जिम्मेदारियाँ"),w(locale,"Time, family, investment and personal circumstances.","நேரம், குடும்பம், முதலீடு மற்றும் தனிப்பட்ட சூழ்நிலைகள்.","समय, परिवार, निवेश और निजी परिस्थितियाँ।")],
 ];
 return <main className="landing">
 <section className="hero"><div className="hero-inner">
 <div className="hero-copy"><p className="eyebrow"><span/> {t("home.badge",locale)}</p><h1>{w(locale,"Your skills matter.","உங்கள் திறன்கள் முக்கியம்.","आपके कौशल मायने रखते हैं।")}<br/><em>{w(locale,"So does your story.","உங்கள் வாழ்க்கையும் முக்கியம்.","आपकी कहानी भी।")}</em></h1>
 <p>{w(locale,"A livelihood path should fit your life. Tell us what you know, what you hope for, and what you need to work around. We’ll help you explore your next step.","உங்கள் வாழ்க்கைக்கு ஏற்ற வாழ்வாதாரப் பாதை. உங்கள் அனுபவம், விருப்பங்கள் மற்றும் தடைகளைச் சொல்லுங்கள். அடுத்த படியை ஆராய உதவுகிறோம்.","आजीविका का रास्ता आपकी जिंदगी के अनुकूल होना चाहिए। अपना अनुभव, इच्छाएँ और सीमाएँ बताइए। हम अगला कदम समझने में मदद करेंगे।")}</p>
 <div className="hero-actions"><Button size="lg" onClick={()=>router.push(startHref)}>{t("home.start",locale)}<ArrowRight/></Button><a href="/demo" className="secondary-link">Explore demo<ArrowRight size={17}/></a><a href="#how-it-works" className="secondary-link">{t("home.howItWorks",locale)}<ArrowRight size={17}/></a></div>
 <div className="hero-points"><span><Check/>{w(locale,"Speak or type","பேசலாம் அல்லது எழுதலாம்","बोलें या लिखें")}</span><span><Check/>{w(locale,"Your choice, always","முடிவு உங்களுடையது","निर्णय हमेशा आपका")}</span></div>
 </div>
 <div className="story-visual" aria-label={w(locale,"How your story becomes a pathway","உங்கள் அனுபவம் பாதையாக மாறும் விதம்","आपकी कहानी से आजीविका के रास्ते तक")}>
 <div className="livelihood-scene" role="img" aria-label={w(locale,"Illustration of people sewing, learning technical skills and planning together","தையல், தொழில்நுட்பக் கற்றல் மற்றும் இணைந்து திட்டமிடும் மனிதர்களின் விளக்கப்படம்","सिलाई, तकनीकी कौशल सीखते और साथ योजना बनाते लोगों का चित्र")} />
 <p className="artwork-caption">{w(locale,"Illustrative scene · not actual beneficiaries","விளக்கக் காட்சி · உண்மையான பயனாளிகள் அல்ல","काल्पनिक चित्र · वास्तविक लाभार्थी नहीं")}</p>
 <div className="story-visual-heading"><span className="small-mark"><LeapMark className="h-8 w-8"/></span><span>LEAP AI</span><span className="visual-caption">{w(locale,"A path shaped around you","உங்களுக்கு ஏற்ற பாதை","आपके अनुकूल रास्ता")}</span></div>

 <p className="visual-question">{w(locale,"“What kind of work feels right for you?”","“எந்த வேலை உங்களுக்கு ஏற்றதாக இருக்கும்?”","“आपके लिए किस तरह का काम सही रहेगा?”")}</p>
 <div className="story-inputs"><div><Fingerprint/><span>{w(locale,"What you know","உங்கள் அனுபவம்","आपका अनुभव")}</span></div><div><Compass/><span>{w(locale,"What you want","உங்கள் விருப்பம்","आपकी इच्छा")}</span></div><div><HeartHandshake/><span>{w(locale,"What life needs","உங்கள் சூழ்நிலை","आपकी परिस्थितियाँ")}</span></div></div>
 <div className="pathway-preview"><span className="preview-icon"><Sprout size={24}/></span><div><p className="eyebrow">{w(locale,"Your next chapter","உங்கள் அடுத்த படி","आपका अगला कदम")}</p><strong>{w(locale,"A practical livelihood pathway","நடைமுறை வாழ்வாதாரப் பாதை","व्यावहारिक आजीविका का रास्ता")}</strong><p>{w(locale,"Clear reasons. Honest uncertainties. Human support.","தெளிவான காரணங்கள். மனித உதவி.","स्पष्ट कारण। ईमानदार जानकारी। मानवीय सहायता।")}</p></div></div>
 <p className="visual-footnote">{w(locale,"How LEAP works · Your assessment will use your own answers.","LEAP செயல்முறை · உங்கள் பதில்களே பயன்படுத்தப்படும்.","LEAP की प्रक्रिया · आकलन आपके अपने उत्तरों पर आधारित होगा।")}</p>
 </div></div></section>
 <section id="how-it-works" className="landing-section"><div className="section-intro"><p className="eyebrow">{t("home.howItWorks",locale)}</p><h2>{w(locale,"Tell us your story. See what fits.","உங்கள் கதையைச் சொல்லுங்கள். பொருத்தமான பாதையை அறியுங்கள்.","अपनी कहानी बताइए। सही विकल्प समझिए।")}</h2><p>{w(locale,"One conversation at a time. You can read, correct and confirm what we understood.","ஒவ்வொரு பதிலையும் படித்து, திருத்தி, உறுதிப்படுத்தலாம்.","हर उत्तर पढ़ें, सुधारें और पुष्टि करें।")}</p></div>
 <div className="steps-grid">{[
 [Mic,w(locale,"Speak naturally","இயல்பாகப் பேசுங்கள்","स्वाभाविक रूप से बोलें"),w(locale,"Tell us about your work and the life around it.","உங்கள் வேலை மற்றும் வாழ்க்கையைப் பகிருங்கள்.","अपने काम और जिंदगी के बारे में बताइए।")],
 [Fingerprint,w(locale,"Check your profile","விவரங்களைச் சரிபாருங்கள்","अपनी जानकारी जाँचें"),w(locale,"Review and confirm the details before they are accepted.","பதிவுக்கு முன் விவரங்களை உறுதிப்படுத்துங்கள்.","जानकारी स्वीकार होने से पहले उसकी पुष्टि करें।")],
 [Compass,w(locale,"Explore your options","வாய்ப்புகளை ஆராயுங்கள்","विकल्प देखें"),w(locale,"Compare pathways and understand the evidence behind them.","பாதைகளையும் அவற்றின் ஆதாரங்களையும் அறியுங்கள்.","रास्तों की तुलना करें और उनके प्रमाण समझें।")],
 [Users,w(locale,"Plan your next step","அடுத்த படியைத் திட்டமிடுங்கள்","अगला कदम तय करें"),w(locale,"Confirm what is uncertain with a person before moving ahead.","முன்னேறுவதற்கு முன் சந்தேகங்களை உதவியாளருடன் உறுதிசெய்யுங்கள்.","आगे बढ़ने से पहले अनिश्चित बातों की समीक्षा कराएँ।")]
 ].map(([Icon,title,copy],i)=>{const I=Icon as typeof Mic;return <article className="step-card" key={i}><div className="step-top"><I size={24}/><span>0{i+1}</span></div><h3>{String(title)}</h3><p>{String(copy)}</p></article>;})}</div></section>
 <section className="experience-section"><div className="experience-art"><div className="experience-icon"><BriefcaseBusiness size={42}/></div><p>{w(locale,"Experience → Evidence → Possibility","அனுபவம் → ஆதாரம் → வாய்ப்பு","अनुभव → प्रमाण → संभावना")}</p><div className="experience-note"><ShieldCheck/><span>{w(locale,"Recognition of Prior Learning","முன் கற்றல் அங்கீகாரம்","पूर्व शिक्षा की मान्यता")}</span></div></div><div><p className="eyebrow">{w(locale,"Experience counts","அனுபவம் மதிப்புடையது","अनुभव की अहमियत")}</p><h2>{w(locale,"Skills don’t only come from certificates.","திறன்கள் சான்றிதழ்களிலிருந்து மட்டும் வருவதில்லை.","कौशल सिर्फ प्रमाणपत्रों से नहीं आते।")}</h2><p>{w(locale,"The work you have learned at home, on a job or in your community matters. LEAP compares that experience with recorded competencies to identify potential RPL routes.","வீட்டிலும் வேலையிலும் சமூகத்திலும் கற்ற அனுபவம் மதிப்புடையது. சாத்தியமான RPL பாதைகளை LEAP கண்டறிய உதவுகிறது.","घर, काम या समुदाय में सीखा अनुभव मायने रखता है। LEAP उस अनुभव से संभावित RPL रास्ते पहचानने में मदद करता है।")}</p><p className="quiet-note">{w(locale,"Potential eligibility needs assessment by an authorized provider. LEAP does not award certification.","தகுதியை அங்கீகரிக்கப்பட்ட நிறுவனம் மதிப்பிட வேண்டும். LEAP சான்றிதழ் வழங்காது.","पात्रता का आकलन अधिकृत संस्था करेगी। LEAP प्रमाणपत्र नहीं देता।")}</p></div></section>
 <section className="landing-section"><div className="section-intro"><p className="eyebrow">{w(locale,"The whole picture","முழுமையான பார்வை","पूरी तस्वीर")}</p><h2>{w(locale,"A pathway has to fit real life.","பாதை நிஜ வாழ்க்கைக்கு ஏற்றதாக இருக்க வேண்டும்.","रास्ता असल जिंदगी के अनुकूल होना चाहिए।")}</h2></div><div className="factor-grid">{factors.map(([Icon,title,copy],i)=>{const I=Icon as typeof Mic;return <article key={i}><I/><h3>{String(title)}</h3><p>{String(copy)}</p></article>;})}</div></section>
 <section className="human-section"><div><p className="eyebrow">{w(locale,"Guidance with accountability","பொறுப்புள்ள வழிகாட்டுதல்","जवाबदेह मार्गदर्शन")}</p><h2>{w(locale,"Clear reasons. People in control.","தெளிவான காரணங்கள். மனிதர்களின் முடிவு.","स्पष्ट कारण। निर्णय लोगों के हाथ में।")}</h2><p>{w(locale,"Every option comes with its evidence and what still needs confirmation. Uncertain cases need human review. You decide your next step with the support you need.","ஒவ்வொரு பாதைக்கும் ஆதாரங்களும் உறுதிப்படுத்த வேண்டிய விவரங்களும் உள்ளன. சந்தேகங்களுக்கு மனித மதிப்பாய்வு தேவை. அடுத்த படியை நீங்கள் முடிவு செய்கிறீர்கள்.","हर विकल्प के साथ प्रमाण और अनिश्चित बातें दिखती हैं। जरूरत पड़ने पर मानवीय समीक्षा होती है। अगला कदम आप तय करते हैं।")}</p></div><div className="human-roles">{[[w(locale,"Field workers","களப் பணியாளர்கள்","क्षेत्र कार्यकर्ता"),w(locale,"Assessment & follow-up","மதிப்பீடு மற்றும் பின்தொடர்வு","आकलन और अनुवर्ती सहायता")],[w(locale,"Facilitators","உதவியாளர்கள்","सहायक"),w(locale,"Evidence & review","ஆதாரங்கள் மற்றும் மதிப்பாய்வு","प्रमाण और समीक्षा")],[w(locale,"District officers","மாவட்ட அதிகாரிகள்","जिला अधिकारी"),w(locale,"Demand, gaps & outcomes","தேவை, இடைவெளி மற்றும் முடிவுகள்","माँग, अंतर और परिणाम")]].map(([title,copy])=><div key={title}><ShieldCheck/><div><h3>{title}</h3><p>{copy}</p></div><ArrowRight/></div>)}</div></section>
 <section className="closing-cta"><Sprout/><h2>{w(locale,"Start with what you know.","உங்களுக்குத் தெரிந்தவற்றிலிருந்து தொடங்குங்கள்.","जो जानते हैं, वहीं से शुरू करें।")}</h2><p>{w(locale,"Your next step starts with a conversation.","உங்கள் அடுத்த படி ஒரு உரையாடலில் தொடங்குகிறது.","अगला कदम एक बातचीत से शुरू होता है।")}</p><Button size="lg" onClick={()=>router.push(startHref)}>{t("home.start",locale)}<ArrowRight/></Button></section>
 <footer className="landing-footer"><strong>LEAP AI</strong><span>{w(locale,"Livelihood guidance that starts with you.","உங்களிடமிருந்து தொடங்கும் வாழ்வாதார வழிகாட்டுதல்.","आजीविका का मार्गदर्शन, जिसकी शुरुआत आपसे होती है।")}</span><span>{w(locale,"Independent decision-support platform","சுயாதீன முடிவு உதவித் தளம்","स्वतंत्र निर्णय सहायता मंच")}</span></footer>
 </main>;
}
