from enum import StrEnum


class UserRole(StrEnum):
    BENEFICIARY = "BENEFICIARY"
    FIELD_WORKER = "FIELD_WORKER"
    FACILITATOR = "FACILITATOR"
    DISTRICT_OFFICER = "DISTRICT_OFFICER"
    ADMIN = "ADMIN"


class SourceType(StrEnum):
    SELF_REPORTED = "SELF_REPORTED"
    FIELD_WORKER = "FIELD_WORKER"
    DOCUMENT = "DOCUMENT"
    SYSTEM_EXTRACTED = "SYSTEM_EXTRACTED"
    NQR = "NQR"
    PM_AJAY = "PM_AJAY"
    SYNTHETIC = "SYNTHETIC"


class Provenance(StrEnum):
    REAL = "REAL"
    SYNTHETIC = "SYNTHETIC"
    USER_REPORTED = "USER_REPORTED"
    FIELD_VERIFIED = "FIELD_VERIFIED"
    SYSTEM_VERIFIED = "SYSTEM_VERIFIED"
    UNVERIFIED = "UNVERIFIED"


class ValidityStatus(StrEnum):
    VALID = "VALID"
    EXPIRED = "EXPIRED"
    UNKNOWN = "UNKNOWN"
    INVALID = "INVALID"


class VerificationStatus(StrEnum):
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    SYNTHETIC = "SYNTHETIC"
    EXPIRED = "EXPIRED"


class InterviewStatus(StrEnum):
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    ABANDONED = "ABANDONED"


class PathwayType(StrEnum):
    FASTEST = "FASTEST"
    ASPIRATIONAL = "ASPIRATIONAL"
    ALTERNATIVE = "ALTERNATIVE"


class PathwayStatus(StrEnum):
    PROPOSED = "PROPOSED"
    SELECTED = "SELECTED"
    REJECTED = "REJECTED"
    COMPLETED = "COMPLETED"


class ConfidenceLevel(StrEnum):
    GREEN = "GREEN"
    AMBER = "AMBER"
    RED = "RED"


class ReviewStatus(StrEnum):
    OPEN = "OPEN"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    EDITED = "EDITED"
    REJECTED = "REJECTED"
    RESOLVED = "RESOLVED"


class EmploymentStatus(StrEnum):
    EMPLOYED = "EMPLOYED"
    SELF_EMPLOYED = "SELF_EMPLOYED"
    SEARCHING = "SEARCHING"
    TRAINING = "TRAINING"
    DROPPED_OUT = "DROPPED_OUT"
    INACTIVE = "INACTIVE"
    UNKNOWN = "UNKNOWN"


class InterventionType(StrEnum):
    NEARBY_TRAINING = "NEARBY_TRAINING"
    BRIDGE_TRAINING = "BRIDGE_TRAINING"
    MOBILITY_SUPPORT = "MOBILITY_SUPPORT"
    ENTERPRISE_CAPITAL = "ENTERPRISE_CAPITAL"
    FLEXIBLE_HOURS = "FLEXIBLE_HOURS"
    COUNSELLING = "COUNSELLING"
