import type { Locale } from "./i18n";

const en = {
  "savedExperience": "Experience saved. Recalculate pathways when you are ready.",
  "skillError": "Could not save skill",
  "savedProfile": "Profile updated",
  "saveError": "Could not save",
  "loadError": "Could not load your profile.",
  "loadingProfile": "Loading your livelihood profile…",
  "emptyProfile": "Your profile is not ready yet",
  "emptyProfileHint": "Complete the assessment first so LEAP can build your livelihood profile.",
  "startAssessment": "Start assessment",
  "profile": "Your profile",
  "editTitle": "Keep your story up to date",
  "travel": "Travel range (km)",
  "capital": "Available capital",
  "missing": "Not provided",
  "aspirationEmpty": "Your next chapter will take shape here.",
  "aspirationHint": "Your aspiration is considered separately from your current experience.",
  "skill": "Skill",
  "know": "What you know",
  "experience": "Experience, skills and real constraints",
  "want": "What you want",
  "possibility": "Aspiration and possibility",
  "addExperience": "Add or update your experience",
  "experienceHint": "Informal work counts. These details are recorded as self-reported, and may support an RPL discussion.",
  "skillWork": "Skill or work",
  "sector": "Sector",
  "years": "Years of experience",
  "savedFollowup": "Follow-up recorded as self-reported.",
  "followupError": "Could not save update",
  "progressHint": "Record what actually happened and the support you need next.",
  "closeForm": "Close form",
  "record": "Record an update",
  "retry": "Try again",
  "loadingFollowup": "Loading follow-ups…",
  "formTitle": "Tell us how things are going",
  "formHint": "Choose the pathway you pursued. Recording an outcome does not certify or verify it.",
  "pathway": "Pathway",
  "choose": "Choose a pathway",
  "point": "Follow-up point",
  "workStatus": "Current work situation",
  "support": "What support would help? (optional)",
  "started": "I started training",
  "completed": "I completed training",
  "certified": "I received a certificate",
  "saveFollowup": "Save follow-up",
  "duplicate": "This follow-up point is already recorded.",
  "gate": "An assessed pathway must be available before you can record progression. Options pending human review cannot be used yet.",
  "early": "Early check-in",
  "livelihood": "Livelihood follow-up",
  "longTerm": "Longer-term outcome",
  "trainingCompleted": "Training completion reported",
  "trainingStarted": "Training start reported",
  "noTraining": "No training milestone reported",
  "certificate": " · Certificate reported",
  "noUpdate": "No update recorded",
  "noFollowup": "No follow-up data yet. Your recorded updates will appear here.",
  "day": "Day",
  "yearUnit": "years",
  "verified": "verified"
};
type JourneyCopy = Record<keyof typeof en, string>;
export const journeyCopy: Record<Locale, JourneyCopy> = {
  en,
  ta: {
  "savedExperience": "அனுபவம் சேமிக்கப்பட்டது. தயாரானதும் பாதைகளை மீண்டும் கணக்கிடுங்கள்.",
  "skillError": "திறனைச் சேமிக்க முடியவில்லை",
  "savedProfile": "சுயவிவரம் புதுப்பிக்கப்பட்டது",
  "saveError": "சேமிக்க முடியவில்லை",
  "loadError": "சுயவிவரத்தை ஏற்ற முடியவில்லை.",
  "loadingProfile": "வாழ்வாதார சுயவிவரம் ஏற்றப்படுகிறது…",
  "emptyProfile": "உங்கள் சுயவிவரம் இன்னும் தயாராகவில்லை",
  "emptyProfileHint": "உங்கள் வாழ்வாதார சுயவிவரத்தை உருவாக்க முதலில் மதிப்பீட்டை முடிக்கவும்.",
  "startAssessment": "மதிப்பீட்டைத் தொடங்கு",
  "profile": "உங்கள் சுயவிவரம்",
  "editTitle": "உங்கள் விவரங்களைப் புதுப்பிக்கவும்",
  "travel": "பயண வரம்பு (கி.மீ.)",
  "capital": "கிடைக்கும் முதலீட்டுத் தொகை",
  "missing": "வழங்கப்படவில்லை",
  "aspirationEmpty": "உங்கள் அடுத்த இலக்கை இங்கே பதிவு செய்யலாம்.",
  "aspirationHint": "உங்கள் இலக்கு, தற்போதைய அனுபவத்திலிருந்து தனியாகக் கருத்தில் கொள்ளப்படுகிறது.",
  "skill": "திறன்",
  "know": "உங்களுக்குத் தெரிந்தவை",
  "experience": "அனுபவம், திறன்கள் மற்றும் நடைமுறைத் தடைகள்",
  "want": "உங்கள் விருப்பம்",
  "possibility": "இலக்கு மற்றும் சாத்தியங்கள்",
  "addExperience": "உங்கள் அனுபவத்தைச் சேர்க்கவும் அல்லது புதுப்பிக்கவும்",
  "experienceHint": "முறைசாரா வேலையும் கணக்கில் கொள்ளப்படும். இவை நீங்கள் தெரிவித்த விவரங்களாகப் பதிவாகும்; RPL கலந்துரையாடலுக்கு உதவலாம்.",
  "skillWork": "திறன் அல்லது வேலை",
  "sector": "துறை",
  "years": "அனுபவ ஆண்டுகள்",
  "savedFollowup": "தொடர் கண்காணிப்பு சுயமாகத் தெரிவித்த பதிவாகச் சேமிக்கப்பட்டது.",
  "followupError": "புதுப்பிப்பைச் சேமிக்க முடியவில்லை",
  "progressHint": "நடந்தவற்றையும் அடுத்து தேவைப்படும் உதவியையும் பதிவுசெய்யுங்கள்.",
  "closeForm": "படிவத்தை மூடு",
  "record": "புதுப்பிப்பைப் பதிவுசெய்",
  "retry": "மீண்டும் முயற்சிக்கவும்",
  "loadingFollowup": "தொடர் கண்காணிப்புப் பதிவுகள் ஏற்றப்படுகின்றன…",
  "formTitle": "உங்கள் முன்னேற்றத்தைப் பகிருங்கள்",
  "formHint": "நீங்கள் தொடர்ந்த பாதையைத் தேர்ந்தெடுக்கவும். முடிவைப் பதிவுசெய்வது அதைச் சான்றளிப்பதோ சரிபார்ப்பதோ அல்ல.",
  "pathway": "வாழ்வாதாரப் பாதை",
  "choose": "ஒரு பாதையைத் தேர்ந்தெடுக்கவும்",
  "point": "தொடர் கண்காணிப்பு நேரம்",
  "workStatus": "தற்போதைய வேலை நிலை",
  "support": "என்ன உதவி தேவை? (விருப்பத்தேர்வு)",
  "started": "பயிற்சியைத் தொடங்கினேன்",
  "completed": "பயிற்சியை முடித்தேன்",
  "certified": "சான்றிதழ் பெற்றேன்",
  "saveFollowup": "தொடர் கண்காணிப்பைச் சேமி",
  "duplicate": "இந்த நேரத்திற்கான பதிவு ஏற்கனவே உள்ளது.",
  "gate": "முன்னேற்றத்தைப் பதிவுசெய்ய மதிப்பிடப்பட்ட பாதை தேவை. மனித மதிப்பாய்வுக்குக் காத்திருக்கும் பாதைகளை இன்னும் பயன்படுத்த முடியாது.",
  "early": "ஆரம்ப நிலை கண்காணிப்பு",
  "livelihood": "வாழ்வாதார தொடர் கண்காணிப்பு",
  "longTerm": "நீண்டகால விளைவு",
  "trainingCompleted": "பயிற்சி முடித்ததாகத் தெரிவிக்கப்பட்டது",
  "trainingStarted": "பயிற்சி தொடங்கியதாகத் தெரிவிக்கப்பட்டது",
  "noTraining": "பயிற்சி முன்னேற்றம் தெரிவிக்கப்படவில்லை",
  "certificate": " · சான்றிதழ் பெற்றதாகத் தெரிவிக்கப்பட்டது",
  "noUpdate": "புதுப்பிப்பு பதிவாகவில்லை",
  "noFollowup": "தொடர் கண்காணிப்புத் தரவு இன்னும் இல்லை. உங்கள் பதிவுகள் இங்கே தோன்றும்.",
  "day": "நாள்",
  "yearUnit": "ஆண்டுகள்",
  "verified": "சரிபார்க்கப்பட்டது"
},
  hi: {
  "savedExperience": "अनुभव सहेजा गया। तैयार होने पर रास्तों की फिर से गणना करें।",
  "skillError": "कौशल सहेजा नहीं जा सका",
  "savedProfile": "प्रोफ़ाइल अपडेट की गई",
  "saveError": "सहेजा नहीं जा सका",
  "loadError": "प्रोफ़ाइल लोड नहीं हो सकी।",
  "loadingProfile": "आजीविका प्रोफ़ाइल लोड हो रही है…",
  "emptyProfile": "आपकी प्रोफ़ाइल अभी तैयार नहीं है",
  "emptyProfileHint": "अपनी आजीविका प्रोफ़ाइल बनाने के लिए पहले आकलन पूरा करें।",
  "startAssessment": "आकलन शुरू करें",
  "profile": "आपकी प्रोफ़ाइल",
  "editTitle": "अपनी जानकारी अपडेट रखें",
  "travel": "यात्रा की सीमा (किमी)",
  "capital": "उपलब्ध पूँजी",
  "missing": "जानकारी नहीं दी गई",
  "aspirationEmpty": "आपका अगला लक्ष्य यहाँ दर्ज हो सकता है।",
  "aspirationHint": "आपके लक्ष्य पर आपके वर्तमान अनुभव से अलग विचार किया जाता है।",
  "skill": "कौशल",
  "know": "आप क्या जानते हैं",
  "experience": "अनुभव, कौशल और वास्तविक बाधाएँ",
  "want": "आप क्या चाहते हैं",
  "possibility": "लक्ष्य और संभावनाएँ",
  "addExperience": "अपना अनुभव जोड़ें या अपडेट करें",
  "experienceHint": "अनौपचारिक काम भी मायने रखता है। ये विवरण स्व-रिपोर्ट के रूप में दर्ज होते हैं और RPL चर्चा में मदद कर सकते हैं।",
  "skillWork": "कौशल या काम",
  "sector": "क्षेत्र",
  "years": "अनुभव के वर्ष",
  "savedFollowup": "फ़ॉलो-अप स्व-रिपोर्ट के रूप में दर्ज किया गया।",
  "followupError": "अपडेट सहेजा नहीं जा सका",
  "progressHint": "जो हुआ और आगे जिस सहायता की ज़रूरत है, उसे दर्ज करें।",
  "closeForm": "फ़ॉर्म बंद करें",
  "record": "अपडेट दर्ज करें",
  "retry": "फिर कोशिश करें",
  "loadingFollowup": "फ़ॉलो-अप लोड हो रहे हैं…",
  "formTitle": "बताएँ कि प्रगति कैसी है",
  "formHint": "आपने जो रास्ता अपनाया, उसे चुनें। परिणाम दर्ज करना उसका प्रमाणीकरण या सत्यापन नहीं है।",
  "pathway": "आजीविका का रास्ता",
  "choose": "एक रास्ता चुनें",
  "point": "फ़ॉलो-अप समय",
  "workStatus": "काम की वर्तमान स्थिति",
  "support": "किस सहायता से मदद मिलेगी? (वैकल्पिक)",
  "started": "मैंने प्रशिक्षण शुरू किया",
  "completed": "मैंने प्रशिक्षण पूरा किया",
  "certified": "मुझे प्रमाणपत्र मिला",
  "saveFollowup": "फ़ॉलो-अप सहेजें",
  "duplicate": "इस समय का फ़ॉलो-अप पहले से दर्ज है।",
  "gate": "प्रगति दर्ज करने के लिए आकलित रास्ता उपलब्ध होना चाहिए। मानव समीक्षा की प्रतीक्षा वाले विकल्प अभी इस्तेमाल नहीं किए जा सकते।",
  "early": "शुरुआती फ़ॉलो-अप",
  "livelihood": "आजीविका फ़ॉलो-अप",
  "longTerm": "लंबी अवधि का परिणाम",
  "trainingCompleted": "प्रशिक्षण पूरा होने की सूचना दी गई",
  "trainingStarted": "प्रशिक्षण शुरू होने की सूचना दी गई",
  "noTraining": "प्रशिक्षण की प्रगति की सूचना नहीं दी गई",
  "certificate": " · प्रमाणपत्र मिलने की सूचना दी गई",
  "noUpdate": "कोई अपडेट दर्ज नहीं है",
  "noFollowup": "अभी फ़ॉलो-अप डेटा नहीं है। आपके दर्ज अपडेट यहाँ दिखेंगे।",
  "day": "दिन",
  "yearUnit": "वर्ष",
  "verified": "सत्यापित"
},
};

const statuses: Record<Locale, Record<string, string>> = {
  "en": {
    "UNKNOWN": "Not known",
    "EMPLOYED": "Employed",
    "SELF_EMPLOYED": "Self-employed",
    "SEARCHING": "Looking for work",
    "TRAINING": "In training",
    "DROPPED_OUT": "Discontinued",
    "INACTIVE": "Inactive",
    "REAL": "Real source",
    "SYNTHETIC": "Synthetic test data",
    "USER_REPORTED": "Self-reported",
    "FIELD_VERIFIED": "Field-verified",
    "SYSTEM_VERIFIED": "System-verified",
    "UNVERIFIED": "Not verified"
  },
  "ta": {
    "UNKNOWN": "தெரியவில்லை",
    "EMPLOYED": "பணியில் உள்ளார்",
    "SELF_EMPLOYED": "சுயதொழில்",
    "SEARCHING": "வேலை தேடுகிறார்",
    "TRAINING": "பயிற்சியில் உள்ளார்",
    "DROPPED_OUT": "தொடரவில்லை",
    "INACTIVE": "செயலில் இல்லை",
    "REAL": "உண்மையான மூலம்",
    "SYNTHETIC": "செயற்கை சோதனைத் தரவு",
    "USER_REPORTED": "சுயமாகத் தெரிவிக்கப்பட்டது",
    "FIELD_VERIFIED": "களத்தில் சரிபார்க்கப்பட்டது",
    "SYSTEM_VERIFIED": "அமைப்பால் சரிபார்க்கப்பட்டது",
    "UNVERIFIED": "சரிபார்க்கப்படவில்லை"
  },
  "hi": {
    "UNKNOWN": "ज्ञात नहीं",
    "EMPLOYED": "नौकरी में",
    "SELF_EMPLOYED": "स्वरोज़गार",
    "SEARCHING": "काम की तलाश में",
    "TRAINING": "प्रशिक्षण में",
    "DROPPED_OUT": "बीच में छोड़ दिया",
    "INACTIVE": "निष्क्रिय",
    "REAL": "वास्तविक स्रोत",
    "SYNTHETIC": "कृत्रिम परीक्षण डेटा",
    "USER_REPORTED": "स्व-रिपोर्ट",
    "FIELD_VERIFIED": "क्षेत्र में सत्यापित",
    "SYSTEM_VERIFIED": "सिस्टम द्वारा सत्यापित",
    "UNVERIFIED": "सत्यापित नहीं"
  }
};

export function journeyStatus(value: string, locale: Locale) {
  return statuses[locale][value] ?? value;
}
