import { extendLocales } from "./locales/extra";
import type { Locale } from "./i18n";

const en = {
  worker: "Field worker workspace",
  workerTitle: "Make the next step easier",
  workerDescription: "Open a beneficiary record to assess, review or follow up.",
  add: "Add beneficiary",
  assessment: "Needs assessment",
  followup: "Needs follow-up",
  review: "Human review",
  rpl: "RPL verification",
  worklist: "Beneficiary worklist",
  search: "Search this page by name or district",
  searchHint: "Search name or district",
  empty: "No matching records on this page.",
  open: "Open record",
  loading: "Loading records…",
  previous: "Previous",
  next: "Next",
  page: "Page",
  retry: "Try again",
  loadError: "Could not load these records. Please try again.",
  officer: "District officer workspace",
  officerTitle: "Recorded livelihood activity",
  officerDescription: "Follow the recorded assessments, training and outcomes across the available dataset.",
  registered: "Beneficiaries registered",
  recommended: "Beneficiaries with pathways",
  started: "Training start reported",
  completed: "Training completion reported",
  positive90: "Positive work status at 90 days",
  active180: "Active status at 180 days",
  scope: "These are aggregate recorded counts across the available dataset. They may include self-reported outcomes and pathways awaiting review. They are not verified placement rates or district-filtered statistics.",
  milestones: "Reported training milestones",
  certified: "Certificate reported",
  missing: "A missing value means data could not be loaded. A zero means no matching record was returned.",
  counts: "Each measure counts beneficiaries, not the number of follow-up entries. Registration does not mean an assessment or profile is complete.",
};

type WorkspaceCopy = { [Key in keyof typeof en]: string };

export const workspaceCopy: Record<Locale, WorkspaceCopy> = extendLocales({
  en,
  ta: {
    worker: "களப்பணியாளர் பணித்தளம்",
    workerTitle: "அடுத்த படியை எளிதாக்குங்கள்",
    workerDescription: "மதிப்பீடு, மதிப்பாய்வு அல்லது தொடர் கண்காணிப்புக்கு பயனாளியின் பதிவைத் திறக்கவும்.",
    add: "பயனாளியைச் சேர்க்கவும்",
    assessment: "மதிப்பீடு தேவை",
    followup: "தொடர் கண்காணிப்பு தேவை",
    review: "மனித மதிப்பாய்வு",
    rpl: "முன் கற்றல் அங்கீகார சரிபார்ப்பு",
    worklist: "பயனாளிகள் பட்டியல்",
    search: "இந்தப் பக்கத்தில் பெயர் அல்லது மாவட்டத்தின் மூலம் தேடவும்",
    searchHint: "பெயர் அல்லது மாவட்டம் தேடவும்",
    empty: "இந்தப் பக்கத்தில் பொருந்தும் பதிவுகள் இல்லை.",
    open: "பதிவைத் திறக்கவும்",
    loading: "பதிவுகள் ஏற்றப்படுகின்றன…",
    previous: "முந்தையது",
    next: "அடுத்தது",
    page: "பக்கம்",
    retry: "மீண்டும் முயலவும்",
    loadError: "பதிவுகளை ஏற்ற முடியவில்லை. மீண்டும் முயலவும்.",
    officer: "மாவட்ட அலுவலர் பணித்தளம்",
    officerTitle: "பதிவான வாழ்வாதார நடவடிக்கைகள்",
    officerDescription: "கிடைக்கும் தரவுகளில் பதிவான மதிப்பீடுகள், பயிற்சி மற்றும் விளைவுகளைப் பார்க்கவும்.",
    registered: "பதிவு செய்யப்பட்ட பயனாளிகள்",
    recommended: "பாதைகள் உள்ள பயனாளிகள்",
    started: "பயிற்சி தொடங்கியதாகப் பதிவு",
    completed: "பயிற்சி முடித்ததாகப் பதிவு",
    positive90: "90-ஆம் நாளில் வேலை அல்லது சுயதொழில்",
    active180: "180-ஆம் நாளில் தொடர்ந்து செயல்படுவோர்",
    scope: "இவை கிடைக்கும் அனைத்துத் தரவுகளின் மொத்தப் பதிவுகள். சுயமாகத் தெரிவித்த விளைவுகளும் மதிப்பாய்வுக்காகக் காத்திருக்கும் பாதைகளும் இதில் இருக்கலாம். இவை சரிபார்க்கப்பட்ட வேலைவாய்ப்பு விகிதங்களோ மாவட்ட வாரியாக வடிகட்டப்பட்ட புள்ளிவிவரங்களோ அல்ல.",
    milestones: "பதிவான பயிற்சி நிலைகள்",
    certified: "சான்றிதழ் பெற்றதாகப் பதிவு",
    missing: "விடுபட்ட மதிப்பு என்பது தரவை ஏற்ற முடியவில்லை என்பதைக் குறிக்கும். பூஜ்ஜியம் என்பது பொருந்தும் பதிவு இல்லை என்பதைக் குறிக்கும்.",
    counts: "ஒவ்வொரு அளவும் பயனாளிகளை எண்ணுகிறது; தொடர் கண்காணிப்புப் பதிவுகளை அல்ல. பதிவு செய்திருப்பது மதிப்பீடு அல்லது சுயவிவரம் முழுமையானது என்று பொருளல்ல.",
  },
  hi: {
    worker: "फील्ड वर्कर कार्यक्षेत्र",
    workerTitle: "अगला कदम आसान बनाएं",
    workerDescription: "मूल्यांकन, समीक्षा या फ़ॉलो-अप के लिए लाभार्थी का रिकॉर्ड खोलें।",
    add: "लाभार्थी जोड़ें",
    assessment: "मूल्यांकन आवश्यक",
    followup: "फ़ॉलो-अप आवश्यक",
    review: "मानवीय समीक्षा",
    rpl: "पूर्व कौशल की मान्यता का सत्यापन",
    worklist: "लाभार्थी सूची",
    search: "इस पृष्ठ पर नाम या जिले से खोजें",
    searchHint: "नाम या जिला खोजें",
    empty: "इस पृष्ठ पर कोई मिलता-जुलता रिकॉर्ड नहीं है।",
    open: "रिकॉर्ड खोलें",
    loading: "रिकॉर्ड लोड हो रहे हैं…",
    previous: "पिछला",
    next: "अगला",
    page: "पृष्ठ",
    retry: "दोबारा कोशिश करें",
    loadError: "रिकॉर्ड लोड नहीं हो सके। दोबारा कोशिश करें।",
    officer: "जिला अधिकारी कार्यक्षेत्र",
    officerTitle: "दर्ज आजीविका गतिविधियां",
    officerDescription: "उपलब्ध डेटा में दर्ज मूल्यांकन, प्रशिक्षण और परिणाम देखें।",
    registered: "पंजीकृत लाभार्थी",
    recommended: "आजीविका रास्तों वाले लाभार्थी",
    started: "प्रशिक्षण शुरू होने की सूचना",
    completed: "प्रशिक्षण पूरा होने की सूचना",
    positive90: "90 दिनों पर नौकरी या स्वरोज़गार",
    active180: "180 दिनों पर सक्रिय स्थिति",
    scope: "ये उपलब्ध डेटा में दर्ज कुल संख्याएं हैं। इनमें स्वयं बताए गए परिणाम और समीक्षा की प्रतीक्षा कर रहे रास्ते शामिल हो सकते हैं। ये सत्यापित रोज़गार दरें या जिले के अनुसार छांटे गए आंकड़े नहीं हैं।",
    milestones: "दर्ज प्रशिक्षण चरण",
    certified: "प्रमाणपत्र मिलने की सूचना",
    missing: "खाली मान का अर्थ है कि डेटा लोड नहीं हो सका। शून्य का अर्थ है कि कोई संबंधित रिकॉर्ड नहीं मिला।",
    counts: "हर माप लाभार्थियों की संख्या है, फ़ॉलो-अप प्रविष्टियों की नहीं। पंजीकरण का अर्थ यह नहीं कि मूल्यांकन या प्रोफ़ाइल पूरी है।",
  },
});
