"""initial_schema

Revision ID: 342db47bc5d6
Revises: 
Create Date: 2026-09-15 12:54:12.787136
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '342db47bc5d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qualification_code', sa.String(length=80), nullable=False),
    sa.Column('qualification_name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=False),
    sa.Column('occupational_role', sa.String(length=180), nullable=False),
    sa.Column('nsqf_level', sa.String(length=20), nullable=True),
    sa.Column('minimum_education', sa.String(length=100), nullable=True),
    sa.Column('minimum_experience_years', sa.Float(), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('qualification_type', sa.String(length=80), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('validity_status', sa.Enum('VALID', 'EXPIRED', 'UNKNOWN', 'INVALID', name='validitystatus'), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.Enum('SELF_REPORTED', 'FIELD_WORKER', 'DOCUMENT', 'SYSTEM_EXTRACTED', 'NQR', 'PM_AJAY', 'SYNTHETIC', name='sourcetype'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qualification_code')
    )
    op.create_index('ix_qualification_sector_validity', 'qualifications', ['sector', 'validity_status'], unique=False)
    op.create_index(op.f('ix_qualifications_sector'), 'qualifications', ['sector'], unique=False)
    op.create_index(op.f('ix_qualifications_validity_status'), 'qualifications', ['validity_status'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('normalized_name', sa.String(length=160), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_normalized_name'), 'skills', ['normalized_name'], unique=True)
    op.create_index(op.f('ix_skills_sector'), 'skills', ['sector'], unique=False)
    op.create_table('sync_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('server_version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'record_type')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('BENEFICIARY', 'FIELD_WORKER', 'FACILITATOR', 'DISTRICT_OFFICER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=40), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('preferred_language', sa.String(length=40), nullable=False),
    sa.Column('digital_literacy', sa.String(length=40), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_beneficiaries_district'), 'beneficiaries', ['district'], unique=False)
    op.create_table('qualification_competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('competency_name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualification_competencies_qualification_id'), 'qualification_competencies', ['qualification_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('training_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('provider_type', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('location_name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('seats_available', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'UNVERIFIED', 'SYNTHETIC', 'EXPIRED', name='verificationstatus'), nullable=False),
    sa.Column('source_type', sa.Enum('SELF_REPORTED', 'FIELD_WORKER', 'DOCUMENT', 'SYSTEM_EXTRACTED', 'NQR', 'PM_AJAY', 'SYNTHETIC', name='sourcetype'), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_training_district_status', 'training_opportunities', ['district', 'verification_status'], unique=False)
    op.create_index(op.f('ix_training_opportunities_district'), 'training_opportunities', ['district'], unique=False)
    op.create_index(op.f('ix_training_opportunities_qualification_id'), 'training_opportunities', ['qualification_id'], unique=False)
    op.create_index(op.f('ix_training_opportunities_verification_status'), 'training_opportunities', ['verification_status'], unique=False)
    op.create_table('beneficiary_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('experience_years', sa.Float(), nullable=False),
    sa.Column('proficiency_level', sa.String(length=50), nullable=True),
    sa.Column('source', sa.Enum('SELF_REPORTED', 'FIELD_WORKER', 'DOCUMENT', 'SYSTEM_EXTRACTED', 'NQR', 'PM_AJAY', 'SYNTHETIC', name='sourcetype'), nullable=False),
    sa.Column('formal_certificate', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beneficiary_id', 'skill_id')
    )
    op.create_index(op.f('ix_beneficiary_skills_beneficiary_id'), 'beneficiary_skills', ['beneficiary_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='interviewstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_beneficiary_id'), 'interview_sessions', ['beneficiary_id'], unique=False)
    op.create_table('livelihood_pathways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=True),
    sa.Column('pathway_type', sa.Enum('FASTEST', 'ASPIRATIONAL', 'ALTERNATIVE', name='pathwaytype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('skill_fit_score', sa.Float(), nullable=False),
    sa.Column('aspiration_fit_score', sa.Float(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('eligibility_score', sa.Float(), nullable=False),
    sa.Column('mobility_score', sa.Float(), nullable=False),
    sa.Column('training_access_score', sa.Float(), nullable=False),
    sa.Column('training_burden_score', sa.Float(), nullable=False),
    sa.Column('outcome_evidence_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.Enum('GREEN', 'AMBER', 'RED', name='confidencelevel'), nullable=False),
    sa.Column('recommended_route', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'SELECTED', 'REJECTED', 'COMPLETED', name='pathwaystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_livelihood_pathways_beneficiary_id'), 'livelihood_pathways', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_livelihood_pathways_confidence_level'), 'livelihood_pathways', ['confidence_level'], unique=False)
    op.create_index(op.f('ix_livelihood_pathways_pathway_type'), 'livelihood_pathways', ['pathway_type'], unique=False)
    op.create_index(op.f('ix_livelihood_pathways_qualification_id'), 'livelihood_pathways', ['qualification_id'], unique=False)
    op.create_index('ix_pathway_beneficiary_status', 'livelihood_pathways', ['beneficiary_id', 'status'], unique=False)
    op.create_table('livelihood_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('current_occupation', sa.String(length=160), nullable=True),
    sa.Column('family_occupation', sa.String(length=160), nullable=True),
    sa.Column('employment_preference', sa.String(length=80), nullable=True),
    sa.Column('aspiration_text', sa.Text(), nullable=True),
    sa.Column('mobility_km', sa.Float(), nullable=True),
    sa.Column('relocation_willingness', sa.Boolean(), nullable=True),
    sa.Column('available_hours_start', sa.Time(), nullable=True),
    sa.Column('available_hours_end', sa.Time(), nullable=True),
    sa.Column('capital_available', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_income_band', sa.String(length=80), nullable=True),
    sa.Column('physical_constraints', sa.Text(), nullable=True),
    sa.Column('family_responsibilities', sa.Text(), nullable=True),
    sa.Column('profile_completion_percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beneficiary_id')
    )
    op.create_table('human_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('pathway_id', sa.Integer(), nullable=True),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('reason_description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'APPROVED', 'EDITED', 'REJECTED', 'RESOLVED', name='reviewstatus'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pathway_id'], ['livelihood_pathways.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_reviews_beneficiary_id'), 'human_reviews', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_reason_code'), 'human_reviews', ['reason_code'], unique=False)
    op.create_index(op.f('ix_human_reviews_status'), 'human_reviews', ['status'], unique=False)
    op.create_index('ix_review_status_created', 'human_reviews', ['status', 'created_at'], unique=False)
    op.create_table('intervention_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('pathway_id', sa.Integer(), nullable=False),
    sa.Column('intervention_type', sa.Enum('NEARBY_TRAINING', 'BRIDGE_TRAINING', 'MOBILITY_SUPPORT', 'ENTERPRISE_CAPITAL', 'FLEXIBLE_HOURS', 'COUNSELLING', name='interventiontype'), nullable=False),
    sa.Column('original_value', sa.JSON(), nullable=False),
    sa.Column('simulated_value', sa.JSON(), nullable=False),
    sa.Column('score_before', sa.Float(), nullable=False),
    sa.Column('score_after', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pathway_id'], ['livelihood_pathways.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervention_simulations_beneficiary_id'), 'intervention_simulations', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_intervention_simulations_pathway_id'), 'intervention_simulations', ['pathway_id'], unique=False)
    op.create_table('interview_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_key', sa.String(length=80), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('speech_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_answers_session_id'), 'interview_answers', ['session_id'], unique=False)
    op.create_table('outcome_followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('pathway_id', sa.Integer(), nullable=False),
    sa.Column('followup_day', sa.Integer(), nullable=False),
    sa.Column('training_started', sa.Boolean(), nullable=False),
    sa.Column('training_completed', sa.Boolean(), nullable=False),
    sa.Column('certified', sa.Boolean(), nullable=False),
    sa.Column('employment_status', sa.Enum('EMPLOYED', 'SELF_EMPLOYED', 'SEARCHING', 'TRAINING', 'DROPPED_OUT', 'INACTIVE', 'UNKNOWN', name='employmentstatus'), nullable=False),
    sa.Column('livelihood_related_to_pathway', sa.Boolean(), nullable=True),
    sa.Column('income_band', sa.String(length=80), nullable=True),
    sa.Column('still_active', sa.Boolean(), nullable=True),
    sa.Column('dropout_reason', sa.Text(), nullable=True),
    sa.Column('support_required', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Enum('REAL', 'SYNTHETIC', 'USER_REPORTED', 'FIELD_VERIFIED', 'SYSTEM_VERIFIED', 'UNVERIFIED', name='provenance'), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pathway_id'], ['livelihood_pathways.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beneficiary_id', 'pathway_id', 'followup_day')
    )
    op.create_index('ix_outcome_day_status', 'outcome_followups', ['followup_day', 'employment_status'], unique=False)
    op.create_index(op.f('ix_outcome_followups_beneficiary_id'), 'outcome_followups', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_outcome_followups_followup_day'), 'outcome_followups', ['followup_day'], unique=False)
    op.create_index(op.f('ix_outcome_followups_pathway_id'), 'outcome_followups', ['pathway_id'], unique=False)
    op.create_table('recommendation_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pathway_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=250), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('SELF_REPORTED', 'FIELD_WORKER', 'DOCUMENT', 'SYSTEM_EXTRACTED', 'NQR', 'PM_AJAY', 'SYNTHETIC', name='sourcetype'), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'UNVERIFIED', 'SYNTHETIC', 'EXPIRED', name='verificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pathway_id'], ['livelihood_pathways.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_evidence_pathway_id'), 'recommendation_evidence', ['pathway_id'], unique=False)
    op.create_table('extracted_profile_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('source_answer_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_answer_id'], ['interview_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_profile_facts_beneficiary_id'), 'extracted_profile_facts', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_extracted_profile_facts_field_name'), 'extracted_profile_facts', ['field_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_profile_facts_field_name'), table_name='extracted_profile_facts')
    op.drop_index(op.f('ix_extracted_profile_facts_beneficiary_id'), table_name='extracted_profile_facts')
    op.drop_table('extracted_profile_facts')
    op.drop_index(op.f('ix_recommendation_evidence_pathway_id'), table_name='recommendation_evidence')
    op.drop_table('recommendation_evidence')
    op.drop_index(op.f('ix_outcome_followups_pathway_id'), table_name='outcome_followups')
    op.drop_index(op.f('ix_outcome_followups_followup_day'), table_name='outcome_followups')
    op.drop_index(op.f('ix_outcome_followups_beneficiary_id'), table_name='outcome_followups')
    op.drop_index('ix_outcome_day_status', table_name='outcome_followups')
    op.drop_table('outcome_followups')
    op.drop_index(op.f('ix_interview_answers_session_id'), table_name='interview_answers')
    op.drop_table('interview_answers')
    op.drop_index(op.f('ix_intervention_simulations_pathway_id'), table_name='intervention_simulations')
    op.drop_index(op.f('ix_intervention_simulations_beneficiary_id'), table_name='intervention_simulations')
    op.drop_table('intervention_simulations')
    op.drop_index('ix_review_status_created', table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_status'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_reason_code'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_beneficiary_id'), table_name='human_reviews')
    op.drop_table('human_reviews')
    op.drop_table('livelihood_profiles')
    op.drop_index('ix_pathway_beneficiary_status', table_name='livelihood_pathways')
    op.drop_index(op.f('ix_livelihood_pathways_qualification_id'), table_name='livelihood_pathways')
    op.drop_index(op.f('ix_livelihood_pathways_pathway_type'), table_name='livelihood_pathways')
    op.drop_index(op.f('ix_livelihood_pathways_confidence_level'), table_name='livelihood_pathways')
    op.drop_index(op.f('ix_livelihood_pathways_beneficiary_id'), table_name='livelihood_pathways')
    op.drop_table('livelihood_pathways')
    op.drop_index(op.f('ix_interview_sessions_beneficiary_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_beneficiary_skills_beneficiary_id'), table_name='beneficiary_skills')
    op.drop_table('beneficiary_skills')
    op.drop_index(op.f('ix_training_opportunities_verification_status'), table_name='training_opportunities')
    op.drop_index(op.f('ix_training_opportunities_qualification_id'), table_name='training_opportunities')
    op.drop_index(op.f('ix_training_opportunities_district'), table_name='training_opportunities')
    op.drop_index('ix_training_district_status', table_name='training_opportunities')
    op.drop_table('training_opportunities')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_qualification_competencies_qualification_id'), table_name='qualification_competencies')
    op.drop_table('qualification_competencies')
    op.drop_index(op.f('ix_beneficiaries_district'), table_name='beneficiaries')
    op.drop_table('beneficiaries')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sync_records')
    op.drop_index(op.f('ix_skills_sector'), table_name='skills')
    op.drop_index(op.f('ix_skills_normalized_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_qualifications_validity_status'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_sector'), table_name='qualifications')
    op.drop_index('ix_qualification_sector_validity', table_name='qualifications')
    op.drop_table('qualifications')
    # ### end Alembic commands ###
